name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq
          npm install -g semver
      - name: Run smoke tests
        run: bats test/
